import assert from "node:assert/strict";
import crypto from "node:crypto";
import test from "node:test";
import { createPostgresBootstrapAuthorityStore } from "../src/bootstrapAuthorityPostgresStore.js";

const D = (value) => crypto.createHash("sha256").update(value).digest("hex");
const DB_NOW = new Date("2026-08-10T10:00:00.000Z");
function poolWith(handler, convergence = {}) { const calls = []; const converged = { missing_columns: [], missing_indexes: [], missing_triggers: [], missing_constraints: [], attestation_columns_converged: true, active_key_index_converged: true, column_semantics_converged: true, check_constraints_converged: true, legacy_state_constraint_converged: true, foreign_keys_converged: true, trigger_definitions_converged: true, ...convergence }; const client = { async query(sql, params = []) { calls.push({ sql, params }); return handler(sql.replace(/\s+/g, " ").trim(), params, calls); }, release() { calls.push({ sql: "RELEASE", params: [] }); } }; return { calls, pool: { async query(sql, params = []) { calls.push({ sql, params, migration: true }); if (sql.includes("required_columns(table_name,column_name)")) return { rowCount: 1, rows: [converged] }; return { rowCount: 0, rows: [] }; }, async connect() { return client; } } }; }
function receipt(tenant = "tenant-a") { return { schema_version: "bootstrap_release_exception_v1", allowed_action: "github.merge", authority_assertion: {}, authority_key_id: "local-pin-key-001", authority_provider: "local_pin", consumed_at: null, core_policy_classification: "BOOTSTRAP_DEADLOCK_VERIFIED", core_policy_verdict_digest: D("policy"), exception_id: "exception-001", expires_at: "2026-08-10T10:10:00.000Z", head_sha: "a".repeat(40), issued_at: "2026-08-10T09:59:00.000Z", max_uses: 1, nonce: "nonce-001", owner_confirmation_digest: D("owner"), post_deploy_obligations_digest: D("post"), pr_number: 223, repository: "owner/repo", required_checks_digest: D("checks"), required_checks_results_digest: D("results"), revoked_at: null, rollback_obligations_digest: D("rollback"), tenant_id: tenant, work_id: "work-001" }; }
function candidate(value) { const receipt_digest = D(JSON.stringify(Object.fromEntries(Object.entries(value).sort(([a], [b]) => a.localeCompare(b))))); return { verification_status: "verified_non_authorizing_candidate", candidate: true, action_authorized: false, execution_authorized: false, host_action_authorized: false, core_join_authorized: false, consumption_authorized: false, receipt_digest, tenant_id: value.tenant_id, exception_id: value.exception_id, work_id: value.work_id, repository: value.repository, pr_number: value.pr_number, head_sha: value.head_sha, allowed_action: value.allowed_action, authority_provider: value.authority_provider, authority_key_id: value.authority_key_id }; }
function consumeArgs(value = receipt()) { return { tenant_id: value.tenant_id, exception_id: value.exception_id, work_id: value.work_id, repository: value.repository, pr_number: value.pr_number, head_sha: value.head_sha, allowed_action: value.allowed_action, authority_key_id: value.authority_key_id, required_checks_digest: value.required_checks_digest, required_checks_results_digest: value.required_checks_results_digest, owner_confirmation_digest: value.owner_confirmation_digest, core_policy_verdict_digest: value.core_policy_verdict_digest, rollback_obligations_digest: value.rollback_obligations_digest, post_deploy_obligations_digest: value.post_deploy_obligations_digest, receipt_digest: D("receipt"), action_request_digest: D("action"), consumed_by: "core-release-gate", target: { repository: value.repository, pr_number: value.pr_number, head_sha: value.head_sha, allowed_action: value.allowed_action } }; }

test("migration is additive, immutable, and supports one un-attested local P1363 key", async () => { const state = poolWith(() => ({ rowCount: 0, rows: [] })); const store = createPostgresBootstrapAuthorityStore({ pool: state.pool }); const ready = await store.initialize(); const sql = state.calls[0].sql; const convergence = state.calls.find((entry) => String(entry.sql).includes("required_columns(table_name,column_name)")).sql; assert.match(sql, /local_pin/); assert.match(sql, /ECDSA_P256_SHA256_P1363/); assert.match(sql, /UNATTESTED_LOCAL_SOFTWARE/); assert.match(sql, /core_bootstrap_one_active_key_per_tenant_idx/); assert.match(sql, /WHERE status = 'ACTIVE'/); assert.match(convergence, /i\.indnkeyatts=1 AND i\.indnatts=1/); assert.match(convergence, /a\.attname='tenant_id'/); assert.match(convergence, /= 'status=''ACTIVE'''/); assert.equal(ready.automatic_trust_installation, false); assert.equal(state.calls.some((entry) => String(entry.sql).startsWith("INSERT INTO core_bootstrap_trust_keys")), false); assert.doesNotMatch(sql, /private_key/i); });

test("migration preserves populated legacy local-pin digest and backfills it as retired legacy-unattested", async () => {
  const state = poolWith(() => ({ rowCount: 0, rows: [] }));
  await createPostgresBootstrapAuthorityStore({ pool: state.pool }).initialize();
  const sql = state.calls[0].sql;
  const legacyRow = { authority_provider: "local_pin", provider_attestation_digest: D("historic-attestation"), attestation_status: null, legacy_local_pin: null };
  assert.equal(legacyRow.provider_attestation_digest, D("historic-attestation"));
  assert.match(sql, /ADD COLUMN IF NOT EXISTS legacy_local_pin boolean/);
  assert.match(sql, /SET legacy_local_pin = \(authority_provider = 'local_pin' AND provider_attestation_digest IS NOT NULL\)/);
  assert.match(sql, /WHEN authority_provider = 'local_pin' THEN 'UNATTESTED_LOCAL_SOFTWARE'/);
  assert.match(sql, /CASE WHEN legacy_local_pin THEN 'RETIRED' ELSE 'ACTIVE' END/);
  assert.match(sql, /legacy_unattested = false OR status IN \('RETIRED','REVOKED'\)/);
  assert.match(sql, /core_bootstrap_legacy_unattested_activation_denied/);
  assert.doesNotMatch(sql, /SET provider_attestation_digest = NULL/);
});

test("initialize rejects a partially converged schema", async () => { const state = poolWith(() => ({ rowCount: 0, rows: [] }), { missing_indexes: ["core_bootstrap_one_active_key_per_tenant_idx"] }); const store = createPostgresBootstrapAuthorityStore({ pool: state.pool }); await assert.rejects(() => store.initialize(), /schema_not_converged/); });

test("initialize rejects semantic index, column, constraint, FK, and trigger drift", async () => {
  for (const field of ["active_key_index_converged", "column_semantics_converged", "check_constraints_converged", "legacy_state_constraint_converged", "foreign_keys_converged", "trigger_definitions_converged"]) {
    const state = poolWith(() => ({ rowCount: 0, rows: [] }), { [field]: false });
    await assert.rejects(() => createPostgresBootstrapAuthorityStore({ pool: state.pool }).initialize(), /schema_not_converged/);
    const query = state.calls.find((entry) => String(entry.sql).includes("required_columns(table_name,column_name)")).sql;
    assert.match(query, /pg_get_constraintdef/);
    assert.match(query, /pg_get_triggerdef/);
    assert.match(query, /core_bootstrap_release_consumptions/);
    assert.match(query, /core_bootstrap_one_active_key_per_tenant_idx/);
  }
});

test("offline trust installation labels local software as un-attested", async () => { const state = poolWith((sql) => { if (sql.startsWith("SELECT k.*,s.status")) return { rowCount: 0, rows: [] }; if (sql.startsWith("SELECT transaction_timestamp")) return { rowCount: 1, rows: [{ database_now: DB_NOW }] }; if (sql.startsWith("INSERT INTO core_bootstrap_trust_keys")) return { rowCount: 1, rows: [{ tenant_id: "tenant-a", authority_key_id: "local-pin-key-001", attestation_status: "UNATTESTED_LOCAL_SOFTWARE" }] }; if (sql.startsWith("SELECT sequence_number")) return { rowCount: 0, rows: [] }; return { rowCount: 1, rows: [] }; }); const store = createPostgresBootstrapAuthorityStore({ pool: state.pool }); await store.installTrustKey({ tenant_id: "tenant-a", authority_key_id: "local-pin-key-001", authority_provider: "local_pin", algorithm: "ECDSA_P256_SHA256_P1363", attestation_status: "UNATTESTED_LOCAL_SOFTWARE", public_key_spki_der: Buffer.alloc(91, 1), public_key_sha256: D("public"), trust_bundle_digest: D("bundle"), provider_attestation_digest: null, genesis_record_digest: D("genesis"), genesis_record: { ceremony: "external_local_pin" } }); const insert = state.calls.find((entry) => entry.sql.startsWith("INSERT INTO core_bootstrap_trust_keys")); assert.ok(insert.params.includes("UNATTESTED_LOCAL_SOFTWARE")); assert.ok(insert.params.includes(null)); });

test("private material is rejected before database mutation", async () => { const state = poolWith(() => ({ rowCount: 0, rows: [] })); const store = createPostgresBootstrapAuthorityStore({ pool: state.pool }); await assert.rejects(() => store.installTrustKey({ tenant_id: "tenant-a", authority_key_id: "local-pin-key-001", private_key: "forbidden" }), /private_material_forbidden/); assert.equal(state.calls.filter((entry) => !entry.migration).length, 0); });

test("consume serializes, uses database time, writes consumption outbox and hash-chain before commit", async () => { const previousHash = D("previous"); const state = poolWith((sql) => { if (sql.startsWith("SELECT c.*,to_jsonb")) return { rowCount: 0, rows: [] }; if (sql.startsWith("SELECT r.receipt_digest")) return { rowCount: 1, rows: [{ receipt_digest: D("receipt") }] }; if (sql.startsWith("SELECT transaction_timestamp")) return { rowCount: 1, rows: [{ database_now: DB_NOW }] }; if (sql.startsWith("INSERT INTO core_bootstrap_release_consumptions")) return { rowCount: 1, rows: [{ consumption_id: "generated", consumed_at: DB_NOW }] }; if (sql.startsWith("INSERT INTO core_bootstrap_action_outbox")) return { rowCount: 1, rows: [{ status: "PENDING" }] }; if (sql.startsWith("SELECT sequence_number")) return { rowCount: 1, rows: [{ sequence_number: 3, event_hash: previousHash }] }; return { rowCount: 1, rows: [] }; }); const store = createPostgresBootstrapAuthorityStore({ pool: state.pool, now: () => 0 }); const result = await store.consume(consumeArgs()); assert.equal(result.idempotent_recovery, false); assert.equal(result.event.previous_event_hash, previousHash); const statements = state.calls.map((entry) => entry.sql); assert.ok(statements.findIndex((sql) => sql.startsWith("INSERT INTO core_bootstrap_release_consumptions")) < statements.findIndex((sql) => sql.startsWith("INSERT INTO core_bootstrap_events"))); });

test("identical consumed request recovers the same locked receipt and outbox without new use or event", async () => { const input = consumeArgs(); const consumptionId = crypto.randomUUID(); const outbox = { consumption_id: consumptionId, action_request_digest: input.action_request_digest, target: input.target, status: "PENDING" }; const persisted = { consumption_id: consumptionId, tenant_id: input.tenant_id, exception_id: input.exception_id, receipt_digest: input.receipt_digest, work_id: input.work_id, repository: input.repository, pr_number: input.pr_number, head_sha: input.head_sha, allowed_action: input.allowed_action, required_checks_digest: input.required_checks_digest, required_checks_results_digest: input.required_checks_results_digest, action_request_digest: input.action_request_digest, persisted_authority_key_id: input.authority_key_id, persisted_owner_confirmation_digest: input.owner_confirmation_digest, persisted_core_policy_verdict_digest: input.core_policy_verdict_digest, persisted_rollback_obligations_digest: input.rollback_obligations_digest, persisted_post_deploy_obligations_digest: input.post_deploy_obligations_digest, outbox }; const state = poolWith((sql) => sql.startsWith("SELECT c.*,to_jsonb") ? { rowCount: 1, rows: [persisted] } : { rowCount: 1, rows: [] }); const store = createPostgresBootstrapAuthorityStore({ pool: state.pool }); const recovered = await store.consume(input); assert.equal(recovered.idempotent_recovery, true); assert.equal(recovered.consumption.consumption_id, consumptionId); assert.equal(recovered.event, null); const recoveryQuery = state.calls.find((entry) => entry.sql.startsWith("SELECT c.*,to_jsonb")).sql; assert.match(recoveryQuery, /JOIN core_bootstrap_action_outbox/); assert.doesNotMatch(recoveryQuery, /LEFT JOIN core_bootstrap_action_outbox/); assert.match(recoveryQuery, /FOR UPDATE OF c,r,o/); assert.equal(state.calls.some((entry) => entry.sql.startsWith("INSERT INTO core_bootstrap_release_consumptions") || entry.sql.startsWith("INSERT INTO core_bootstrap_events")), false); });

test("changed persisted receipt policy digest remains replay deny", async () => { const input = consumeArgs(); const outbox = { action_request_digest: input.action_request_digest, target: input.target, status: "PENDING" }; const state = poolWith((sql) => sql.startsWith("SELECT c.*,to_jsonb") ? { rowCount: 1, rows: [{ receipt_digest: input.receipt_digest, work_id: input.work_id, repository: input.repository, pr_number: input.pr_number, head_sha: input.head_sha, allowed_action: input.allowed_action, required_checks_digest: input.required_checks_digest, required_checks_results_digest: input.required_checks_results_digest, action_request_digest: input.action_request_digest, persisted_authority_key_id: input.authority_key_id, persisted_owner_confirmation_digest: input.owner_confirmation_digest, persisted_core_policy_verdict_digest: D("different-core-verdict"), persisted_rollback_obligations_digest: input.rollback_obligations_digest, persisted_post_deploy_obligations_digest: input.post_deploy_obligations_digest, outbox }] } : { rowCount: 1, rows: [] }); const store = createPostgresBootstrapAuthorityStore({ pool: state.pool }); await assert.rejects(() => store.consume(input), /replayed/); });

test("changed action digest remains replay deny", async () => { const input = consumeArgs(); const state = poolWith((sql) => sql.startsWith("SELECT c.*,to_jsonb") ? { rowCount: 1, rows: [{ receipt_digest: input.receipt_digest, work_id: input.work_id, repository: input.repository, pr_number: input.pr_number, head_sha: input.head_sha, allowed_action: input.allowed_action, required_checks_digest: input.required_checks_digest, required_checks_results_digest: input.required_checks_results_digest, action_request_digest: D("different-ticket"), outbox: { action_request_digest: D("different-ticket"), target: input.target } }] } : { rowCount: 1, rows: [] }); const store = createPostgresBootstrapAuthorityStore({ pool: state.pool }); await assert.rejects(() => store.consume(input), /replayed/); assert.ok(state.calls.some((entry) => entry.sql === "ROLLBACK")); });

test("cross-tenant consume fails closed without disclosing the other tenant", async () => { const state = poolWith((sql) => { if (sql.startsWith("SELECT c.*,to_jsonb") || sql.startsWith("SELECT r.receipt_digest")) return { rowCount: 0, rows: [] }; return { rowCount: 1, rows: [] }; }); const store = createPostgresBootstrapAuthorityStore({ pool: state.pool }); await assert.rejects(() => store.consume(consumeArgs(receipt("tenant-b"))), /not_eligible/); const eligibility = state.calls.find((entry) => entry.sql.startsWith("SELECT r.receipt_digest")); assert.equal(eligibility.params[0], "tenant-b"); });

test("read is tenant scoped and returns no cross-tenant record", async () => { const state = poolWith((sql) => sql.startsWith("SELECT * FROM core_bootstrap_release_receipts") ? { rowCount: 0, rows: [] } : { rowCount: 1, rows: [] }); const store = createPostgresBootstrapAuthorityStore({ pool: state.pool }); assert.equal(await store.read({ tenant_id: "tenant-b", exception_id: "exception-001" }), null); const query = state.calls.find((entry) => entry.sql.startsWith("SELECT * FROM core_bootstrap_release_receipts")); assert.deepEqual(query.params, ["tenant-b", "exception-001"]); });
