import assert from "node:assert/strict";import crypto from "node:crypto";import {readFile} from "node:fs/promises";import test from "node:test";
import{NYRA_PRECORE_DECISIONS,NYRA_PRECORE_SCHEMA_VERSION,canonicalNyraPrecoreJson,createPostgresNyraPrecoreDecisionStore,nyraPrecoreDigest,verifyNyraPrecoreRecord}from"../src/nyraPrecoreDecisionStore.js";
const U={project:"11111111-1111-4111-8111-111111111111",repository:"22222222-2222-4222-8222-222222222222",work:"33333333-3333-4333-8333-333333333333",change:"44444444-4444-4444-8444-444444444444",plan:"55555555-5555-4555-8555-555555555555"},scope={tenant_id:"tenant-a",project_id:U.project,repository_id:U.repository,work_id:U.work,change_id:U.change,plan_id:U.plan};
function input(overrides={}){return{scope,subject:{base_revision:"a".repeat(40),candidate_revision:"b".repeat(40),change_digest:"c".repeat(64)},authority_refs:Object.fromEntries(["genesis","intent","icf","software_reality_graph","native_plan","security_assessment","research_evidence_bundle","authority_snapshot"].map(n=>[n,{id:`${n}:1`,revision:"revision:1",digest:"d".repeat(64)}])),decision:{kind:"PROPOSE",proposed_next_step:"PROPOSE_TO_CORE_REVIEW",summary:"Submit advisory evidence to Core",risks:[],conditions:[],rollback_requirements:[],open_challenges:[],knowledge_gaps:[]},evidence:{claim_ids:[],tool_result_ids:[],coverage:{sufficient:true},freshness_evaluated_at:"2026-08-17T10:00:00.000Z",fresh_until:"2026-08-17T10:10:00.000Z",evidence_digest:"e".repeat(64)},agent_instance_id:"nyra:agent-1",expected_sequence:0,expected_parent_digest:null,idempotency_key:"idem:one",...overrides};}
function fixture(initialClock=new Date("2026-08-17T10:00:01.000Z"),{advanceClockOnSign=null}={}){const keys=crypto.generateKeyPairSync("ed25519"),receipts=[],events=[];let clock=initialClock;const query=async(sql,params=[])=>{const q=String(sql);if(q.includes("pg_advisory_xact_lock")){assert.match(params[0],/^[a-f0-9]{64}$/);assert.doesNotMatch(params[0],/\0/);return{rows:[]};}if(["BEGIN","COMMIT","ROLLBACK"].includes(q)||q.includes("SET TRANSACTION"))return{rows:[]};
 if(q.includes("payload->>'idempotency_key'=$4")){const r=receipts.find(x=>x.tenant===params[0]&&x.work===params[1]&&x.plan===params[2]&&x.payload.idempotency_key===params[3]);return{rows:r?[{request_digest:r.request,payload:r.payload}]:[]};}
 if(q.includes("ORDER BY chain_sequence DESC LIMIT 1 FOR UPDATE")){const r=receipts.at(-1);return{rows:r?[{receipt_id:r.payload.decision_id,chain_sequence:r.payload.chain.sequence,payload_digest:r.payload.chain.record_digest}]:[]};}
 if(q==="SELECT clock_timestamp() AS now")return{rows:[{now:clock}]};
 if(q.startsWith("INSERT INTO core_continuity_native_receipts")){receipts.push({tenant:params[0],work:params[1],plan:params[2],payload:JSON.parse(params[5]),request:params[9]});return{rows:[]};}
 if(q.startsWith("SELECT work_id FROM core_continuity_works"))return{rows:[{work_id:params[1]}]};
 if(q.includes("FROM core_continuity_events")&&q.includes("LIMIT 1 FOR UPDATE")){const e=events.at(-1);return{rows:e?[{sequence_number:e.sequence,event_hash:e.hash}]:[]};}
 if(q.startsWith("INSERT INTO core_continuity_events")){events.push({sequence:params[3],hash:params[6]});return{rows:[]};}
 if(q.includes(" AS superseded FROM core_continuity_native_receipts d")){const r=params[0]===scope.tenant_id?receipts.find(x=>x.payload.decision_id===params[3]&&x.payload.scope.project_id===params[4]&&x.payload.scope.repository_id===params[5]&&x.payload.scope.change_id===params[6]):null;return{rows:r?[{payload:r.payload,superseded:receipts.some(n=>n.payload.supersedes_decision_id===r.payload.decision_id)}]:[]};}
 if(q.includes("ORDER BY chain_sequence DESC LIMIT $8"))return{rows:[...receipts].reverse().map(r=>({payload:r.payload}))};
 if(q.includes("ORDER BY created_at DESC,chain_sequence DESC LIMIT 1"))return{rows:receipts.length?[{payload:receipts.at(-1).payload}]:[]};
 if(q.includes("ORDER BY chain_sequence")&&!q.includes("DESC"))return{rows:receipts.map(r=>({payload:r.payload}))};
 throw new Error(`unhandled:${q.slice(0,120)}`);};const client={query,release(){}},pool={connect:async()=>client,query:async(sql,params=[])=>String(sql).includes("BEGIN;")?{rows:[]}:query(sql,params)};
 const signer={algorithm:"Ed25519",authority_scope:"ADVISORY_NON_EXECUTABLE",key_id:"nyra-precore-key-1",async signPayload(payload,purpose){assert.equal(purpose,"nyra.precore.decision.v1");if(advanceClockOnSign)clock=new Date(advanceClockOnSign);return crypto.sign(null,payload,keys.privateKey).toString("base64url");}},verifier={async verifyPayload({payload,signature,key_id,algorithm,purpose,tenant_id}){return key_id===signer.key_id&&algorithm==="Ed25519"&&purpose==="nyra.precore.decision.v1"&&tenant_id==="tenant-a"&&crypto.verify(null,payload,keys.publicKey,Buffer.from(signature,"base64url"));}};
 return{store:createPostgresNyraPrecoreDecisionStore({pool,signer,verifier}),receipts,events,verifier,setClock(value){clock=new Date(value);}};}
test("migration extends Work Continuity receipts and creates no authority or key store",async()=>{const sql=await readFile(new URL("../migrations/20260817_nyra_precore_decision_v1.sql",import.meta.url),"utf8");assert.match(sql,/ALTER TABLE core_continuity_native_receipts/);assert.match(sql,/chain_sequence bigint/);assert.match(sql,/parent_payload_digest char\(64\)/);assert.match(sql,/receipt_type='software_precore_decision'/);assert.match(sql,/payload->>'execution_authorized'/);assert.doesNotMatch(sql,/CREATE TABLE/);assert.doesNotMatch(sql,/core_bootstrap_trust_keys/);assert.doesNotMatch(sql,/APPROVE|AUTO_/);});
test("canonical digest and enum remain advisory",()=>{assert.equal(nyraPrecoreDigest({b:2,a:1}),nyraPrecoreDigest({a:1,b:2}));assert.equal(canonicalNyraPrecoreJson({b:2,a:1}),'{"a":1,"b":2}');assert.deepEqual(NYRA_PRECORE_DECISIONS,["PROPOSE","CHALLENGE","ABSTAIN","RECOMMEND_BLOCK"]);});
test("receipt and continuity event append atomically with chaining, replay and supersession",async()=>{const{store,receipts,events}=fixture(),first=await store.generate(input());assert.equal(first.execution_authorized,false);assert.equal(first.chain.sequence,1);assert.equal(receipts.length,1);assert.equal(events.length,1);const replay=await store.generate(input());assert.equal(replay.decision_id,first.decision_id);assert.equal(receipts.length,1);const second=await store.generate(input({decision:{...input().decision,kind:"CHALLENGE",proposed_next_step:"COLLECT_EVIDENCE"},expected_sequence:1,expected_parent_digest:first.chain.record_digest,supersedes_decision_id:first.decision_id,idempotency_key:"idem:two"}));assert.equal(second.chain.parent_digest,first.chain.record_digest);assert.equal(receipts.length,2);assert.equal(events.length,2);assert.equal((await store.verify(scope,second.decision_id)).valid,true);const stale=await store.verify(scope,second.decision_id,{"authority_refs.icf.digest":"f".repeat(64)});assert.equal(stale.valid,false);assert.ok(stale.reasons.includes("STALE_AUTHORITY_REFS_ICF_DIGEST"));const old=await store.verify(scope,first.decision_id);assert.equal(old.valid,false);assert.ok(old.reasons.includes("DECISION_SUPERSEDED"));});
test("new head must explicitly supersede old head",async()=>{const{store}=fixture(),first=await store.generate(input());await assert.rejects(()=>store.generate(input({expected_sequence:1,expected_parent_digest:first.chain.record_digest,idempotency_key:"idem:two"})),/nyra_precore_supersession_head_required/);});
test("client authority, stale CAS, cross-scope, legacy and tampering fail closed",async()=>{const{store,verifier}=fixture();await assert.rejects(()=>store.generate(input({execution_authorized:true})),/nyra_precore_client_authority_forbidden/);const first=await store.generate(input());await assert.rejects(()=>store.generate(input({idempotency_key:"idem:stale"})),/nyra_precore_cas_conflict/);assert.equal(await store.read({...scope,tenant_id:"tenant-b"},first.decision_id),null);const tampered=structuredClone(first);tampered.decision.summary="tampered";assert.equal(await verifyNyraPrecoreRecord(tampered,verifier),false);assert.equal(await verifyNyraPrecoreRecord({schema_version:NYRA_PRECORE_SCHEMA_VERSION,execution_authorized:false,authority_scope:"ADVISORY_NON_EXECUTABLE"},verifier),false);assert.equal(await verifyNyraPrecoreRecord({...first,schema_version:"legacy_receipt_v0"},verifier),false);});
test("verification reads the complete chain rather than a 200-record window",async()=>{const{store,receipts}=fixture();let parent=null;for(let i=1;i<=205;i++){const base=input({expected_sequence:i-1,expected_parent_digest:parent,idempotency_key:`idem:${i}`,supersedes_decision_id:i===1?null:receipts.at(-1).payload.decision_id});const r=await store.generate(base);parent=r.chain.record_digest;}assert.equal((await store.verify(scope,receipts.at(-1).payload.decision_id)).valid,true);});
test("DB-time expiry invalidates a signed decision and current Work head is readable",async()=>{const f=fixture(),record=await f.store.generate(input());assert.equal((await f.store.readHeadForWork({tenant_id:scope.tenant_id,work_id:scope.work_id})).decision_id,record.decision_id);f.setClock("2026-08-17T10:11:00.000Z");const verification=await f.store.verify(scope,record.decision_id);assert.equal(verification.valid,false);assert.ok(verification.reasons.includes("EVIDENCE_EXPIRED"));});
test("signer latency cannot persist evidence that expires during signing",async()=>{const f=fixture(new Date("2026-08-17T10:00:01.000Z"),{advanceClockOnSign:"2026-08-17T10:11:00.000Z"});await assert.rejects(()=>f.store.generate(input()),/nyra_precore_evidence_expired_during_signing/);assert.equal(f.receipts.length,0);assert.equal(f.events.length,0);});
