export const AI_GATEWAY_PAYLOAD_SCHEMA = {
  type: "object",
  required: ["user_request"],
  properties: {
    tenant_id: { type: "string" },
    adapter: { type: "string", enum: ["generic", "chatgpt", "codex", "site_suite", "smart_desk", "skinharmony_core"] },
    action_type: { type: "string" },
    requested_action: { type: "object" },
    user_request: { type: "string" },
    llm_output: { type: "string" },
    context: { type: "object" },
    runtime_state: { type: "object" },
    role_scope: { type: "object" },
    flow_pressure: { type: ["number", "object"] },
    gateway_mode: { type: "string", enum: ["advisory", "rewrite", "hard-gating", "execution_orchestration"] },
    mode: { type: "string", enum: ["advisory", "rewrite", "hard-gating", "execution_orchestration"] },
    variants: { type: "array" },
    owner_confirmed: { type: "boolean" },
  },
};

export const AI_GATEWAY_VERDICT_SCHEMA = {
  type: "object",
  required: ["decision", "risk", "confidence", "executionAllowed", "requiresOwnerConfirmation"],
  properties: {
    decision: { type: "string", enum: ["allow_advisory", "review", "block"] },
    decision_state: { type: "string", enum: ["ready", "attention", "blocked", "observe"] },
    risk: {
      type: "object",
      required: ["band"],
      properties: {
        score: { type: ["number", "null"] },
        band: { type: "string", enum: ["low", "medium", "high"] },
        reasons: { type: "array", items: { type: "string" } },
      },
    },
    confidence: { type: "number" },
    warnings: { type: "array", items: { type: "string" } },
    policyFlags: { type: "object" },
    executionAllowed: { type: "boolean" },
    recommendedVariant: { type: "object" },
    requiresOwnerConfirmation: { type: "boolean" },
    action_mediation: {
      type: "object",
      properties: {
        state: { type: "string", enum: ["allow", "rewrite", "confirm", "defer", "sandbox", "block", "rollback_required"] },
        execution_allowed: { type: "boolean" },
        owner_confirmation_required: { type: "boolean" },
        sandbox_required: { type: "boolean" },
        rollback_required: { type: "boolean" },
        rewrite_allowed: { type: "boolean" },
        blocked: { type: "boolean" },
        next_step: { type: "string" },
      },
    },
    explainability: {
      type: "object",
      properties: {
        audience: { type: "string" },
        mode: { type: "string" },
        summary: { type: "string" },
        why: { type: "string" },
        risk_readout: { type: "object" },
        safe_alternative: { type: "string" },
        owner_message: { type: "string" },
      },
    },
    commercial_explanation: { type: "string" },
    final_output: { type: "string" },
    audit_id: { type: "string" },
  },
};
