import crypto from "node:crypto";
import fs from "node:fs/promises";
import { fileURLToPath } from "node:url";

const MIGRATION=fileURLToPath(new URL("../migrations/20260817_nyra_precore_decision_v1.sql",import.meta.url));
export const NYRA_PRECORE_SCHEMA_VERSION="nyra_precore_decision_v1";
export const NYRA_PRECORE_DECISIONS=Object.freeze(["PROPOSE","CHALLENGE","ABSTAIN","RECOMMEND_BLOCK"]);
const KINDS=new Set(NYRA_PRECORE_DECISIONS),STEPS=new Set(["PROPOSE_TO_CORE_REVIEW","REMEDIATE","COLLECT_EVIDENCE","STOP_AND_REVIEW"]),UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,SHA=/^[a-f0-9]{64}$/,ID=/^[A-Za-z0-9][A-Za-z0-9._:/-]{1,239}$/;
function fail(code){const e=new Error(code);e.code=code;throw e;} function plain(v){return v&&typeof v==="object"&&!Array.isArray(v)&&Object.getPrototypeOf(v)===Object.prototype;}
export function canonicalNyraPrecoreJson(v){if(v===null||typeof v==="string"||typeof v==="boolean")return JSON.stringify(v);if(typeof v==="number"&&Number.isFinite(v))return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(canonicalNyraPrecoreJson).join(",")}]`;if(!plain(v))fail("nyra_precore_noncanonical_value");return`{${Object.keys(v).filter(k=>v[k]!==undefined).sort().map(k=>`${JSON.stringify(k)}:${canonicalNyraPrecoreJson(v[k])}`).join(",")}}`;}
export const nyraPrecoreDigest=(v)=>crypto.createHash("sha256").update(canonicalNyraPrecoreJson(v)).digest("hex");
const uuid=(v,c)=>{v=String(v||"");if(!UUID.test(v))fail(c);return v.toLowerCase();},digest=(v,c)=>{v=String(v||"").toLowerCase();if(!SHA.test(v))fail(c);return v;},id=(v,c)=>{v=String(v||"");if(!ID.test(v))fail(c);return v;};
const list=(v,c)=>{if(!Array.isArray(v)||v.length>500)fail(c);return[...new Set(v.map(String).map(x=>x.trim()).filter(Boolean))].sort();};
const ref=(v,c)=>{if(!plain(v))fail(c);return{id:id(v.id,c),revision:id(v.revision,c),digest:digest(v.digest,c)};};
function normalizeScope(v){return{tenant_id:id(v?.tenant_id,"tenant_id_invalid"),project_id:uuid(v?.project_id,"project_id_invalid"),repository_id:id(v?.repository_id,"repository_id_invalid"),work_id:uuid(v?.work_id,"work_id_invalid"),change_id:uuid(v?.change_id,"change_id_invalid"),plan_id:uuid(v?.plan_id,"plan_id_invalid")};}
function normalize(input){if(!plain(input))fail("nyra_precore_input_invalid");if(input.execution_authorized!==undefined||input.authority_scope!==undefined)fail("nyra_precore_client_authority_forbidden");const scope=normalizeScope(input.scope),kind=String(input.decision?.kind||""),step=String(input.decision?.proposed_next_step||"");if(!KINDS.has(kind))fail("nyra_precore_decision_kind_invalid");if(!STEPS.has(step))fail("nyra_precore_next_step_invalid");const authority_refs={};for(const n of["genesis","intent","icf","software_reality_graph","native_plan","security_assessment","research_evidence_bundle","authority_snapshot"])authority_refs[n]=ref(input.authority_refs?.[n],`nyra_precore_${n}_ref_invalid`);const summary=String(input.decision?.summary||"").trim();if(!summary||summary.length>8000)fail("nyra_precore_summary_invalid");let freshness,freshUntil;try{freshness=new Date(input.evidence?.freshness_evaluated_at).toISOString();freshUntil=new Date(input.evidence?.fresh_until).toISOString();}catch{fail("nyra_precore_freshness_invalid");}if(Date.parse(freshUntil)<=Date.parse(freshness))fail("nyra_precore_freshness_invalid");return{scope,subject:{base_revision:id(input.subject?.base_revision,"nyra_precore_base_revision_invalid"),candidate_revision:id(input.subject?.candidate_revision,"nyra_precore_candidate_revision_invalid"),change_digest:digest(input.subject?.change_digest,"nyra_precore_change_digest_invalid")},authority_refs,decision:{kind,proposed_next_step:step,summary,risks:list(input.decision?.risks||[],"nyra_precore_risks_invalid"),conditions:list(input.decision?.conditions||[],"nyra_precore_conditions_invalid"),rollback_requirements:list(input.decision?.rollback_requirements||[],"nyra_precore_rollback_invalid"),open_challenges:list(input.decision?.open_challenges||[],"nyra_precore_challenges_invalid"),knowledge_gaps:list(input.decision?.knowledge_gaps||[],"nyra_precore_gaps_invalid")},evidence:{claim_ids:list(input.evidence?.claim_ids||[],"nyra_precore_claims_invalid"),tool_result_ids:list(input.evidence?.tool_result_ids||[],"nyra_precore_tools_invalid"),coverage:plain(input.evidence?.coverage)?input.evidence.coverage:{},freshness_evaluated_at:freshness,fresh_until:freshUntil,evidence_digest:digest(input.evidence?.evidence_digest,"nyra_precore_evidence_digest_invalid")},agent_instance_id:id(input.agent_instance_id,"nyra_precore_agent_invalid"),expected_sequence:Number(input.expected_sequence||0),expected_parent_digest:input.expected_parent_digest==null?null:digest(input.expected_parent_digest,"nyra_precore_parent_digest_invalid"),supersedes_decision_id:input.supersedes_decision_id==null?null:uuid(input.supersedes_decision_id,"nyra_precore_supersedes_invalid"),idempotency_key:id(input.idempotency_key,"nyra_precore_idempotency_invalid")};}
export const NYRA_PRECORE_SIGNING_PURPOSE="nyra.precore.decision.v1";
const signingPayload=d=>Buffer.from(`${NYRA_PRECORE_SCHEMA_VERSION}\0${d}`,"utf8");
function unsigned(n,{decision_id,sequence,parent,created_at,key_id}){return{schema_version:NYRA_PRECORE_SCHEMA_VERSION,nsct_version:"1.1",decision_id,scope:n.scope,subject:n.subject,authority_refs:n.authority_refs,decision:n.decision,evidence:n.evidence,chain:{sequence,parent_digest:parent,created_at},provenance:{producer:"nyra",agent_instance_id:n.agent_instance_id,signer_key_id:key_id,signed_at:created_at},supersedes_decision_id:n.supersedes_decision_id,idempotency_key:n.idempotency_key,execution_authorized:false,authority_scope:"ADVISORY_NON_EXECUTABLE"};}
function digestValid(r){if(!plain(r)||!plain(r.chain)||!plain(r.provenance))return false;const c=structuredClone(r),d=c.chain.record_digest;delete c.chain.record_digest;delete c.provenance.signature;delete c.provenance.signature_algorithm;return SHA.test(String(d||""))&&nyraPrecoreDigest(c)===d;}
export async function verifyNyraPrecoreRecord(record,verifier){if(!record||record.schema_version!==NYRA_PRECORE_SCHEMA_VERSION||record.execution_authorized!==false||record.authority_scope!=="ADVISORY_NON_EXECUTABLE"||!digestValid(record)||typeof verifier?.verifyPayload!=="function")return false;return await verifier.verifyPayload({payload:signingPayload(record.chain.record_digest),signature:record.provenance.signature,key_id:record.provenance.signer_key_id,algorithm:record.provenance.signature_algorithm,purpose:NYRA_PRECORE_SIGNING_PURPOSE,tenant_id:record.scope.tenant_id})===true;}
export function createPostgresNyraPrecoreDecisionStore({pool,signer,verifier}={}){if(!pool?.connect||typeof signer?.signPayload!=="function"||signer.algorithm!=="Ed25519"||signer.authority_scope!=="ADVISORY_NON_EXECUTABLE"||!ID.test(String(signer.key_id||""))||typeof verifier?.verifyPayload!=="function")fail("nyra_precore_signer_unavailable");
 const decode=r=>r&&(typeof r.payload==="string"?JSON.parse(r.payload):r.payload);async function initialize(){await pool.query(await fs.readFile(MIGRATION,"utf8"));return{schema_version:NYRA_PRECORE_SCHEMA_VERSION,mode:"ADVISORY"};}async function tx(fn,ro=false){const c=await pool.connect();try{await c.query("BEGIN");if(ro)await c.query("SET TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY");const v=await fn(c);await c.query("COMMIT");return v;}catch(e){try{await c.query("ROLLBACK");}catch{}throw e;}finally{c.release();}}
 async function appendEvent(c,n,record){await c.query("SELECT work_id FROM core_continuity_works WHERE tenant_id=$1 AND work_id=$2 FOR UPDATE",[n.scope.tenant_id,n.scope.work_id]);const p=await c.query("SELECT sequence_number,event_hash FROM core_continuity_events WHERE tenant_id=$1 AND work_id=$2 ORDER BY sequence_number DESC LIMIT 1 FOR UPDATE",[n.scope.tenant_id,n.scope.work_id]);const seq=Number(p.rows[0]?.sequence_number||0)+1,prev=p.rows[0]?.event_hash||null,payload={receipt_id:record.decision_id,plan_id:n.scope.plan_id,record_digest:record.chain.record_digest,decision_kind:record.decision.kind,execution_authorized:false,authority_scope:"ADVISORY_NON_EXECUTABLE"},hash=nyraPrecoreDigest({tenant_id:n.scope.tenant_id,work_id:n.scope.work_id,sequence_number:seq,event_type:"software_precore_decision_recorded",payload,previous_event_hash:prev});await c.query("INSERT INTO core_continuity_events(tenant_id,work_id,event_id,sequence_number,event_type,payload,previous_event_hash,event_hash,created_by) VALUES($1,$2,$3,$4,'software_precore_decision_recorded',$5::jsonb,$6,$7,$8)",[n.scope.tenant_id,n.scope.work_id,crypto.randomUUID(),seq,JSON.stringify(payload),prev,hash,n.agent_instance_id]);}
 async function generate(input,{transaction=null}={}){const n=normalize(input),req=nyraPrecoreDigest(n),s=n.scope;const operation=async c=>{const lockKey=nyraPrecoreDigest({tenant_id:s.tenant_id,work_id:s.work_id,plan_id:s.plan_id});await c.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[lockKey]);const replay=await c.query("SELECT request_digest,payload FROM core_continuity_native_receipts WHERE tenant_id=$1 AND work_id=$2 AND plan_id=$3 AND receipt_type='software_precore_decision' AND payload->>'idempotency_key'=$4",[s.tenant_id,s.work_id,s.plan_id,n.idempotency_key]);if(replay.rows[0]){if(replay.rows[0].request_digest!==req)fail("nyra_precore_idempotency_conflict");return decode(replay.rows[0]);}const h=await c.query("SELECT receipt_id,chain_sequence,payload_digest FROM core_continuity_native_receipts WHERE tenant_id=$1 AND work_id=$2 AND plan_id=$3 AND receipt_type='software_precore_decision' ORDER BY chain_sequence DESC LIMIT 1 FOR UPDATE",[s.tenant_id,s.work_id,s.plan_id]),sequence=Number(h.rows[0]?.chain_sequence||0)+1,parent=h.rows[0]?.payload_digest||null;if(n.expected_sequence!==sequence-1||n.expected_parent_digest!==parent)fail("nyra_precore_cas_conflict");if(sequence>1&&n.supersedes_decision_id!==h.rows[0]?.receipt_id)fail("nyra_precore_supersession_head_required");if(sequence===1&&n.supersedes_decision_id)fail("nyra_precore_supersession_invalid");const now=new Date((await c.query("SELECT clock_timestamp() AS now")).rows[0].now).toISOString();if(Date.parse(n.evidence.fresh_until)<=Date.parse(now))fail("nyra_precore_evidence_expired");const decision_id=crypto.randomUUID(),u=unsigned(n,{decision_id,sequence,parent,created_at:now,key_id:signer.key_id}),rd=nyraPrecoreDigest(u),signature=await signer.signPayload(signingPayload(rd),NYRA_PRECORE_SIGNING_PURPOSE),record={...u,chain:{...u.chain,record_digest:rd},provenance:{...u.provenance,signature_algorithm:"Ed25519",signature}};if(!await verifyNyraPrecoreRecord(record,verifier))fail("nyra_precore_signature_invalid");const insertionNow=new Date((await c.query("SELECT clock_timestamp() AS now")).rows[0].now).toISOString();if(Date.parse(n.evidence.fresh_until)<=Date.parse(insertionNow))fail("nyra_precore_evidence_expired_during_signing");await c.query("INSERT INTO core_continuity_native_receipts(tenant_id,work_id,plan_id,receipt_id,receipt_type,agent_id,payload,payload_digest,created_by,chain_sequence,parent_payload_digest,request_digest,signer_key_id,signature_algorithm,signature,signed_at,authority_scope,created_at) VALUES($1,$2,$3,$4,'software_precore_decision',$5,$6::jsonb,$7,$5,$8,$9,$10,$11,'Ed25519',$12,$13,'ADVISORY_NON_EXECUTABLE',$13)",[s.tenant_id,s.work_id,s.plan_id,decision_id,n.agent_instance_id,JSON.stringify(record),rd,sequence,parent,req,signer.key_id,signature,now]);await appendEvent(c,n,record);return record;};return transaction?operation(transaction):tx(operation);}
 async function read(scope,decisionId,db=pool){const s=normalizeScope(scope),r=await db.query("SELECT d.payload,EXISTS(SELECT 1 FROM core_continuity_native_receipts n WHERE n.tenant_id=d.tenant_id AND n.work_id=d.work_id AND n.plan_id=d.plan_id AND n.receipt_type='software_precore_decision' AND n.payload->>'supersedes_decision_id'=d.receipt_id::text) AS superseded FROM core_continuity_native_receipts d WHERE d.tenant_id=$1 AND d.work_id=$2 AND d.plan_id=$3 AND d.receipt_type='software_precore_decision' AND d.receipt_id=$4 AND d.payload->'scope'->>'project_id'=$5 AND d.payload->'scope'->>'repository_id'=$6 AND d.payload->'scope'->>'change_id'=$7",[s.tenant_id,s.work_id,s.plan_id,uuid(decisionId,"decision_id_invalid"),s.project_id,s.repository_id,s.change_id]);return r.rows[0]?{record:decode(r.rows[0]),superseded:r.rows[0].superseded}:null;}
 async function list(scope,{limit=100,before_sequence}={}){const s=normalizeScope(scope),l=Math.min(200,Math.max(1,Number(limit)||100)),r=await pool.query("SELECT payload FROM core_continuity_native_receipts WHERE tenant_id=$1 AND work_id=$2 AND plan_id=$3 AND receipt_type='software_precore_decision' AND payload->'scope'->>'project_id'=$4 AND payload->'scope'->>'repository_id'=$5 AND payload->'scope'->>'change_id'=$6 AND ($7::bigint IS NULL OR chain_sequence<$7) ORDER BY chain_sequence DESC LIMIT $8",[s.tenant_id,s.work_id,s.plan_id,s.project_id,s.repository_id,s.change_id,before_sequence??null,l]);return r.rows.map(decode);}
 async function readHeadForWork({tenant_id,work_id}={}){const tenant=id(tenant_id,"tenant_id_invalid"),work=uuid(work_id,"work_id_invalid"),r=await pool.query("SELECT payload FROM core_continuity_native_receipts WHERE tenant_id=$1 AND work_id=$2 AND receipt_type='software_precore_decision' ORDER BY created_at DESC,chain_sequence DESC LIMIT 1",[tenant,work]);return decode(r.rows[0])||null;}
 async function verify(scope,decisionId,expected={}){const s=normalizeScope(scope);return tx(async db=>{const rows=await db.query("SELECT payload FROM core_continuity_native_receipts WHERE tenant_id=$1 AND work_id=$2 AND plan_id=$3 AND receipt_type='software_precore_decision' AND payload->'scope'->>'project_id'=$4 AND payload->'scope'->>'repository_id'=$5 AND payload->'scope'->>'change_id'=$6 ORDER BY chain_sequence",[s.tenant_id,s.work_id,s.plan_id,s.project_id,s.repository_id,s.change_id]),records=rows.rows.map(decode),reasons=[];let parent=null,seq=0;for(const r of records){seq++;if(r.chain.sequence!==seq||r.chain.parent_digest!==parent||!await verifyNyraPrecoreRecord(r,verifier))reasons.push("CHAIN_OR_SIGNATURE_INVALID");parent=r.chain.record_digest;}const item=await read(s,decisionId,db);if(!item)reasons.push("DECISION_NOT_FOUND");else{if(item.superseded)reasons.push("DECISION_SUPERSEDED");const dbNow=Date.parse(new Date((await db.query("SELECT clock_timestamp() AS now")).rows[0].now).toISOString());if(!Number.isFinite(Date.parse(item.record?.evidence?.fresh_until))||Date.parse(item.record.evidence.fresh_until)<=dbNow)reasons.push("EVIDENCE_EXPIRED");for(const[p,v]of Object.entries(expected)){const o=p.split(".").reduce((a,k)=>a?.[k],item.record);if(o!==v)reasons.push(`STALE_${p.toUpperCase().replaceAll(".","_")}`);}}return{valid:reasons.length===0,reasons:[...new Set(reasons)].sort(),head_digest:parent,record:item?.record||null};},true);}
 return Object.freeze({initialize,generate,read,list,readHeadForWork,verify});}
