DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM core_entity360_snapshots LIMIT 1)
     OR EXISTS (SELECT 1 FROM core_entity360_registry LIMIT 1)
     OR EXISTS (SELECT 1 FROM core_entity360_shadow_receipts LIMIT 1)
     OR EXISTS (SELECT 1 FROM core_entity360_backfill_events LIMIT 1) THEN
    RAISE EXCEPTION 'ENTITY360_DOWN_MIGRATION_REFUSED_AUTHORITATIVE_ROWS';
  END IF;
  RAISE EXCEPTION 'ENTITY360_DOWN_MIGRATION_DISABLED_USE_FEATURE_FLAG';
END $$;
