import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

type Asset = {
  symbol: string;
  yahoo: string;
  name: string;
  class: string;
  region: string;
};

const ROOT = process.cwd().endsWith("/universal-core") ? join(process.cwd(), "..") : process.cwd();
const OUT_PATH = join(ROOT, "universal-core", "config", "nyra_world_market_universe.json");

function asset(symbol: string, name: string, assetClass: string, region: string, yahoo = symbol): Asset {
  return { symbol, yahoo, name, class: assetClass, region };
}

const assets: Asset[] = [
  asset("SPY", "S&P 500 ETF", "equity_index", "US"),
  asset("QQQ", "Nasdaq 100 ETF", "equity_index", "US"),
  asset("DIA", "Dow Jones ETF", "equity_index", "US"),
  asset("IWM", "Russell 2000 ETF", "equity_index", "US"),
  asset("MDY", "S&P MidCap 400 ETF", "equity_index", "US"),
  asset("RSP", "Equal Weight S&P 500 ETF", "equity_index", "US"),
  asset("ACWI", "Global equities ETF", "global_equity", "Global"),
  asset("VT", "Total world stock ETF", "global_equity", "Global"),
  asset("VEA", "Developed ex-US ETF", "global_equity", "Developed"),
  asset("VWO", "Emerging markets ETF", "global_equity", "Emerging"),
  asset("EFA", "EAFE developed markets ETF", "global_equity", "Developed"),
  asset("EEM", "Emerging markets ETF", "global_equity", "Emerging"),

  asset("XLK", "Technology sector ETF", "sector_us", "US"),
  asset("XLC", "Communication services sector ETF", "sector_us", "US"),
  asset("XLY", "Consumer discretionary sector ETF", "sector_us", "US"),
  asset("XLP", "Consumer staples sector ETF", "sector_us", "US"),
  asset("XLE", "Energy sector ETF", "sector_us", "US"),
  asset("XLF", "Financial sector ETF", "sector_us", "US"),
  asset("XLV", "Health care sector ETF", "sector_us", "US"),
  asset("XLI", "Industrial sector ETF", "sector_us", "US"),
  asset("XLB", "Materials sector ETF", "sector_us", "US"),
  asset("XLU", "Utilities sector ETF", "sector_us", "US"),
  asset("XLRE", "Real estate sector ETF", "sector_us", "US"),
  asset("XBI", "Biotech ETF", "sector_us", "US"),
  asset("SMH", "Semiconductor ETF", "sector_us", "US"),
  asset("SOXX", "Semiconductor ETF", "sector_us", "US"),
  asset("KRE", "Regional banks ETF", "sector_us", "US"),
  asset("ITB", "US home construction ETF", "sector_us", "US"),
  asset("IYR", "US real estate ETF", "sector_us", "US"),
  asset("JETS", "Airlines ETF", "sector_us", "US"),
  asset("ARKK", "Innovation/growth ETF", "thematic_growth", "US"),
  asset("BOTZ", "Robotics and AI ETF", "thematic_growth", "Global"),
  asset("ROBO", "Robotics ETF", "thematic_growth", "Global"),
  asset("CIBR", "Cybersecurity ETF", "thematic_growth", "US"),
  asset("HACK", "Cybersecurity ETF", "thematic_growth", "US"),
  asset("ICLN", "Clean energy ETF", "thematic_growth", "Global"),
  asset("TAN", "Solar ETF", "thematic_growth", "Global"),
  asset("URA", "Uranium ETF", "thematic_commodity", "Global"),
  asset("LIT", "Lithium and battery ETF", "thematic_commodity", "Global"),
  asset("COPX", "Copper miners ETF", "thematic_commodity", "Global"),
  asset("GDX", "Gold miners ETF", "thematic_commodity", "Global"),
  asset("GDXJ", "Junior gold miners ETF", "thematic_commodity", "Global"),
  asset("SIL", "Silver miners ETF", "thematic_commodity", "Global"),

  asset("EWJ", "Japan ETF", "country_equity", "Japan"),
  asset("EWG", "Germany ETF", "country_equity", "Germany"),
  asset("EWU", "United Kingdom ETF", "country_equity", "UK"),
  asset("EWQ", "France ETF", "country_equity", "France"),
  asset("EWI", "Italy ETF", "country_equity", "Italy"),
  asset("EWP", "Spain ETF", "country_equity", "Spain"),
  asset("EWL", "Switzerland ETF", "country_equity", "Switzerland"),
  asset("EWN", "Netherlands ETF", "country_equity", "Netherlands"),
  asset("EWD", "Sweden ETF", "country_equity", "Sweden"),
  asset("EWK", "Belgium ETF", "country_equity", "Belgium"),
  asset("EWO", "Austria ETF", "country_equity", "Austria"),
  asset("EIRL", "Ireland ETF", "country_equity", "Ireland"),
  asset("ENOR", "Norway ETF", "country_equity", "Norway"),
  asset("EDEN", "Denmark ETF", "country_equity", "Denmark"),
  asset("EFNL", "Finland ETF", "country_equity", "Finland"),
  asset("EPOL", "Poland ETF", "country_equity", "Poland"),
  asset("GREK", "Greece ETF", "country_equity", "Greece"),
  asset("TUR", "Turkey ETF", "country_equity", "Turkey"),
  asset("EWZ", "Brazil ETF", "country_equity", "Brazil"),
  asset("EWW", "Mexico ETF", "country_equity", "Mexico"),
  asset("ECH", "Chile ETF", "country_equity", "Chile"),
  asset("EPU", "Peru ETF", "country_equity", "Peru"),
  asset("ARGT", "Argentina ETF", "country_equity", "Argentina"),
  asset("EWC", "Canada ETF", "country_equity", "Canada"),
  asset("EWA", "Australia ETF", "country_equity", "Australia"),
  asset("ENZL", "New Zealand ETF", "country_equity", "New Zealand"),
  asset("MCHI", "China ETF", "country_equity", "China"),
  asset("FXI", "China large-cap ETF", "country_equity", "China"),
  asset("KWEB", "China internet ETF", "country_equity", "China"),
  asset("ASHR", "China A-shares ETF", "country_equity", "China"),
  asset("EWH", "Hong Kong ETF", "country_equity", "Hong Kong"),
  asset("EWT", "Taiwan ETF", "country_equity", "Taiwan"),
  asset("EWY", "South Korea ETF", "country_equity", "South Korea"),
  asset("INDA", "India ETF", "country_equity", "India"),
  asset("EPI", "India earnings ETF", "country_equity", "India"),
  asset("EIDO", "Indonesia ETF", "country_equity", "Indonesia"),
  asset("EWM", "Malaysia ETF", "country_equity", "Malaysia"),
  asset("EPHE", "Philippines ETF", "country_equity", "Philippines"),
  asset("THD", "Thailand ETF", "country_equity", "Thailand"),
  asset("VNM", "Vietnam ETF", "country_equity", "Vietnam"),
  asset("EWS", "Singapore ETF", "country_equity", "Singapore"),
  asset("EZA", "South Africa ETF", "country_equity", "South Africa"),
  asset("EGPT", "Egypt ETF", "country_equity", "Egypt"),
  asset("KSA", "Saudi Arabia ETF", "country_equity", "Saudi Arabia"),
  asset("UAE", "UAE ETF", "country_equity", "UAE"),
  asset("QAT", "Qatar ETF", "country_equity", "Qatar"),
  asset("ISRA", "Israel ETF", "country_equity", "Israel"),

  asset("TLT", "US long treasury ETF", "bond", "US"),
  asset("IEF", "US 7-10Y treasury ETF", "bond", "US"),
  asset("SHY", "US short treasury ETF", "bond", "US"),
  asset("BIL", "Treasury bills ETF", "cash_proxy", "US"),
  asset("TIP", "US TIPS ETF", "bond", "US"),
  asset("LQD", "Investment grade corporate bond ETF", "bond", "US"),
  asset("HYG", "High yield corporate bond ETF", "bond", "US"),
  asset("JNK", "High yield bond ETF", "bond", "US"),
  asset("EMB", "EM sovereign debt ETF", "bond", "Emerging"),
  asset("BNDX", "International bond ETF", "bond", "Global"),
  asset("BWX", "International treasury ETF", "bond", "Global"),
  asset("MUB", "Municipal bond ETF", "bond", "US"),

  asset("GLD", "Gold ETF", "commodity_proxy", "Global"),
  asset("IAU", "Gold ETF", "commodity_proxy", "Global"),
  asset("SLV", "Silver ETF", "commodity_proxy", "Global"),
  asset("PPLT", "Platinum ETF", "commodity_proxy", "Global"),
  asset("PALL", "Palladium ETF", "commodity_proxy", "Global"),
  asset("CPER", "Copper ETF", "commodity_proxy", "Global"),
  asset("USO", "Oil ETF", "commodity_proxy", "Global"),
  asset("BNO", "Brent oil ETF", "commodity_proxy", "Global"),
  asset("UNG", "Natural gas ETF", "commodity_proxy", "Global"),
  asset("DBA", "Agriculture ETF", "commodity_proxy", "Global"),
  asset("DBC", "Broad commodity ETF", "commodity_proxy", "Global"),
  asset("DBB", "Base metals ETF", "commodity_proxy", "Global"),
  asset("DBP", "Precious metals ETF", "commodity_proxy", "Global"),
  asset("CORN", "Corn ETF", "commodity_proxy", "Global"),
  asset("WEAT", "Wheat ETF", "commodity_proxy", "Global"),
  asset("SOYB", "Soybean ETF", "commodity_proxy", "Global"),
  asset("CANE", "Sugar ETF", "commodity_proxy", "Global"),
  asset("BAL", "Cotton ETF", "commodity_proxy", "Global"),
  asset("JO", "Coffee ETN", "commodity_proxy", "Global"),
  asset("NIB", "Cocoa ETN", "commodity_proxy", "Global"),
  asset("COW", "Livestock ETN", "commodity_proxy", "Global"),

  asset("UUP", "US dollar ETF", "fx_proxy", "FX"),
  asset("FXE", "Euro ETF", "fx_proxy", "FX"),
  asset("FXY", "Japanese yen ETF", "fx_proxy", "FX"),
  asset("FXB", "British pound ETF", "fx_proxy", "FX"),
  asset("FXA", "Australian dollar ETF", "fx_proxy", "FX"),
  asset("FXC", "Canadian dollar ETF", "fx_proxy", "FX"),
  asset("FXF", "Swiss franc ETF", "fx_proxy", "FX"),
  asset("CYB", "Chinese yuan ETF", "fx_proxy", "FX"),
  asset("CEW", "Emerging currency ETF", "fx_proxy", "FX"),

  asset("SH", "Short S&P 500 ETF", "inverse_equity", "US"),
  asset("PSQ", "Short Nasdaq 100 ETF", "inverse_equity", "US"),
  asset("DOG", "Short Dow ETF", "inverse_equity", "US"),
  asset("RWM", "Short Russell 2000 ETF", "inverse_equity", "US"),
  asset("SDS", "2x short S&P 500 ETF", "inverse_equity", "US"),
  asset("QID", "2x short Nasdaq 100 ETF", "inverse_equity", "US"),
  asset("SQQQ", "3x short Nasdaq 100 ETF", "inverse_equity", "US"),
  asset("SPXU", "3x short S&P 500 ETF", "inverse_equity", "US"),
  asset("TZA", "3x short Russell 2000 ETF", "inverse_equity", "US"),
  asset("YANG", "3x short China ETF", "inverse_equity", "China"),
  asset("DRV", "3x short real estate ETF", "inverse_equity", "US"),
  asset("TMV", "3x short 20Y treasury ETF", "inverse_bond", "US"),

  asset("AAPL", "Apple", "single_stock", "US"),
  asset("MSFT", "Microsoft", "single_stock", "US"),
  asset("NVDA", "Nvidia", "single_stock", "US"),
  asset("AMZN", "Amazon", "single_stock", "US"),
  asset("GOOGL", "Alphabet", "single_stock", "US"),
  asset("META", "Meta", "single_stock", "US"),
  asset("TSLA", "Tesla", "single_stock", "US"),
  asset("AVGO", "Broadcom", "single_stock", "US"),
  asset("AMD", "AMD", "single_stock", "US"),
  asset("INTC", "Intel", "single_stock", "US"),
  asset("ORCL", "Oracle", "single_stock", "US"),
  asset("CRM", "Salesforce", "single_stock", "US"),
  asset("ADBE", "Adobe", "single_stock", "US"),
  asset("NFLX", "Netflix", "single_stock", "US"),
  asset("DIS", "Disney", "single_stock", "US"),
  asset("JPM", "JPMorgan", "single_stock", "US"),
  asset("BAC", "Bank of America", "single_stock", "US"),
  asset("GS", "Goldman Sachs", "single_stock", "US"),
  asset("MS", "Morgan Stanley", "single_stock", "US"),
  asset("V", "Visa", "single_stock", "US"),
  asset("MA", "Mastercard", "single_stock", "US"),
  asset("PYPL", "PayPal", "single_stock", "US"),
  asset("COST", "Costco", "single_stock", "US"),
  asset("WMT", "Walmart", "single_stock", "US"),
  asset("HD", "Home Depot", "single_stock", "US"),
  asset("MCD", "McDonald's", "single_stock", "US"),
  asset("NKE", "Nike", "single_stock", "US"),
  asset("KO", "Coca-Cola", "single_stock", "US"),
  asset("PEP", "PepsiCo", "single_stock", "US"),
  asset("PG", "Procter & Gamble", "single_stock", "US"),
  asset("JNJ", "Johnson & Johnson", "single_stock", "US"),
  asset("PFE", "Pfizer", "single_stock", "US"),
  asset("LLY", "Eli Lilly", "single_stock", "US"),
  asset("MRK", "Merck", "single_stock", "US"),
  asset("UNH", "UnitedHealth", "single_stock", "US"),
  asset("XOM", "Exxon Mobil", "single_stock", "US"),
  asset("CVX", "Chevron", "single_stock", "US"),
  asset("COP", "ConocoPhillips", "single_stock", "US"),
  asset("CAT", "Caterpillar", "single_stock", "US"),
  asset("DE", "Deere", "single_stock", "US"),
  asset("BA", "Boeing", "single_stock", "US"),
  asset("GE", "General Electric", "single_stock", "US"),
  asset("HON", "Honeywell", "single_stock", "US"),
  asset("NOC", "Northrop Grumman", "single_stock", "US"),
  asset("LMT", "Lockheed Martin", "single_stock", "US"),
  asset("PLTR", "Palantir", "single_stock", "US"),
  asset("COIN", "Coinbase", "single_stock", "US"),
  asset("MSTR", "MicroStrategy", "single_stock", "US"),
  asset("UBER", "Uber", "single_stock", "US"),
  asset("SHOP", "Shopify", "single_stock", "Canada"),
  asset("BABA", "Alibaba", "single_stock", "China"),
  asset("PDD", "PDD Holdings", "single_stock", "China"),
  asset("BIDU", "Baidu", "single_stock", "China"),
  asset("TSM", "Taiwan Semiconductor", "single_stock", "Taiwan"),
  asset("ASML", "ASML", "single_stock", "Netherlands"),
  asset("NVO", "Novo Nordisk", "single_stock", "Denmark"),
  asset("SAP", "SAP", "single_stock", "Germany"),
  asset("TM", "Toyota", "single_stock", "Japan"),
  asset("SONY", "Sony", "single_stock", "Japan"),
  asset("HSBC", "HSBC", "single_stock", "UK"),
  asset("SHEL", "Shell", "single_stock", "UK"),
  asset("RIO", "Rio Tinto", "single_stock", "UK"),
  asset("UL", "Unilever", "single_stock", "UK"),
  asset("BP", "BP", "single_stock", "UK"),
  asset("VALE", "Vale", "single_stock", "Brazil"),
  asset("PBR", "Petrobras", "single_stock", "Brazil"),
  asset("MELI", "MercadoLibre", "single_stock", "Latin America"),

  asset("BTC-EUR", "Bitcoin EUR", "crypto", "Global", "BTC-EUR"),
  asset("ETH-EUR", "Ethereum EUR", "crypto", "Global", "ETH-EUR"),
  asset("SOL-EUR", "Solana EUR", "crypto", "Global", "SOL-EUR"),
  asset("LINK-EUR", "Chainlink EUR", "crypto", "Global", "LINK-EUR"),
  asset("BNB-USD", "BNB USD", "crypto", "Global", "BNB-USD"),
  asset("XRP-USD", "XRP USD", "crypto", "Global", "XRP-USD"),
  asset("ADA-USD", "Cardano USD", "crypto", "Global", "ADA-USD"),
  asset("DOGE-USD", "Dogecoin USD", "crypto", "Global", "DOGE-USD"),
  asset("AVAX-USD", "Avalanche USD", "crypto", "Global", "AVAX-USD"),
  asset("DOT-USD", "Polkadot USD", "crypto", "Global", "DOT-USD"),
  asset("TRX-USD", "TRON USD", "crypto", "Global", "TRX-USD"),
  asset("MATIC-USD", "Polygon USD", "crypto", "Global", "MATIC-USD")
];

const unique = Array.from(new Map(assets.map((item) => [item.symbol, item])).values());
const output = {
  version: "nyra_world_market_universe_v2_global_proxy",
  generated_at: new Date().toISOString(),
  note: "Broad liquid global proxy universe for paper discovery. Not every world market is directly executable; this covers liquid ETFs, sectors, countries, commodities, FX proxies, inverse ETFs, crypto, and large global ADRs.",
  assets: unique
};

mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, `${JSON.stringify(output, null, 2)}\n`);
console.log(JSON.stringify({
  ok: true,
  path: OUT_PATH,
  assets: unique.length,
  classes: Array.from(new Set(unique.map((item) => item.class))).sort(),
  regions: Array.from(new Set(unique.map((item) => item.region))).sort()
}, null, 2));
